### ISSUE TITLE
listUsers() - field `samaccountname` is not defined in the `User` properties

### ISSUE THREAD

**Issue by tbigby-kristin** [onelogin/onelogin-java-sdk#58]
I am using the OneLogin Java SDK for an identity management integration, and have started with listing the users in OneLogin.

The SDK believes that the AD username parameter is named as `samaccount_name`, however the API actually returns the field `samaccountname` (with no underscore).

This causes the following exception:

```
Caused by: java.lang.IllegalArgumentException: The field `samaccountname` in the JSON string is not defined in the `User` properties. JSON: {"directory_id":null,"external_id":null,"state":1,"last_login":"2023-02-23T22:59:05.182Z","invitation_sent_at":"2022-06-28T21:40:06.758Z","locked_until":null,"activated_at":"2022-06-28T21:40:06.779Z","group_id":null,"id":1815*****,"distinguished_name":null,"member_of":null,"password_changed_at":"2023-02-07T23:33:56.904Z","username":"","invalid_login_attempts":0,"lastname":"Test","email":"***@***.***.nz","samaccountname":null,"created_at":"2022-06-28T21:40:06.788Z","firstname":"Test","status":1,"updated_at":"2023-02-23T22:59:05.478Z","phone":""}
        at com.onelogin.sdk.model.User.validateJsonObject(User.java:1352)
        at com.onelogin.sdk.model.User$CustomTypeAdapterFactory$1.read(User.java:1466)
        at com.onelogin.sdk.model.User$CustomTypeAdapterFactory$1.read(User.java:1456)
        at com.google.gson.TypeAdapter$1.read(TypeAdapter.java:199)
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
        at com.google.gson.Gson.fromJson(Gson.java:991)
        at com.google.gson.Gson.fromJson(Gson.java:956)
        at com.google.gson.Gson.fromJson(Gson.java:905)
        at com.onelogin.sdk.JSON.deserialize(JSON.java:252)
        at com.onelogin.sdk.ApiClient.deserialize(ApiClient.java:845)
        at com.onelogin.sdk.ApiClient.handleResponse(ApiClient.java:1055)
        at com.onelogin.sdk.ApiClient.execute(ApiClient.java:979)
        at com.onelogin.sdk.DefaultApi.listUsersWithHttpInfo(DefaultApi.java:13068)
        at com.onelogin.sdk.DefaultApi.listUsers(DefaultApi.java:13026)
```

The sample response in the API docs (https://developers.onelogin.com/api-docs/2/users/list-users) shows that the field name should be `samaccountname`.

I have regenerated the SDK and submitted pull request #57 , which resolves this issue. Please review.

Thanks very much, Tony

**Comment by Jmfwolf** [comment]
The naming was corrected in the newest version. Please let me know if there are any issues with it

**Comment by tbigby-kristin** [comment]
Sorry, I struck another similar issue and switched to using Feign to call the REST API directly, so I can't test directly.

However, it does appear on a quick glance to be correct now. Will close this issue and the pull request.

**Comment by RanjithAruchamy** [comment]
@Jmfwolf I could see this issue still exist in `3.0.1` version. 
I could see the latest version as `3.0.1` in the [mvn](https://mvnrepository.com/artifact/com.onelogin/onelogin-java-sdk) which is released on Nov 2023.

```
The field `samaccountname` in the JSON string is not defined in the `User` properties.
```
