### ISSUE TITLE
The field `pagination` in the JSON string is not defined in the `GetGroups200Response` properties

### ISSUE THREAD

**Issue by tprus** [onelogin/onelogin-java-sdk#62]
Listing groups not working at all:

Exception in thread "main" java.lang.IllegalArgumentException: The field `pagination` in the JSON string is not defined in the `GetGroups200Response` properties. JSON: {"status":{"error":false,"code":200,"type":"success","message":"Success"},"pagination":{"before_cursor":null,"after_cursor":null,"previous_link":null,"next_link":null},"data":[{"id":502836,"name":"test","reference":null}]}
	at com.onelogin.client.model.GetGroups200Response.validateJsonObject(GetGroups200Response.java:189)
	at com.onelogin.client.model.GetGroups200Response$CustomTypeAdapterFactory$1.read(GetGroups200Response.java:233)
	at com.onelogin.client.model.GetGroups200Response$CustomTypeAdapterFactory$1.read(GetGroups200Response.java:223)
	at com.google.gson.TypeAdapter$1.read(TypeAdapter.java:199)
	at com.google.gson.Gson.fromJson(Gson.java:963)
	at com.google.gson.Gson.fromJson(Gson.java:928)
	at com.google.gson.Gson.fromJson(Gson.java:877)
	at com.onelogin.client.JSON.deserialize(JSON.java:325)
	at com.onelogin.client.ApiClient.deserialize(ApiClient.java:989)
	at com.onelogin.client.ApiClient.handleResponse(ApiClient.java:1199)
	at com.onelogin.client.ApiClient.execute(ApiClient.java:1123)
	at com.onelogin.client.api.GroupsApi.getGroupsWithHttpInfo(GroupsApi.java:309)
	at com.onelogin.client.api.GroupsApi.getGroups(GroupsApi.java:289)

<dependency>
  <groupId>com.onelogin</groupId>
  <artifactId>onelogin-java-sdk</artifactId>
  <version>3.1.1</version>
</dependency>
            
            
GroupsApi groupsApi = new GroupsApi(defaultClient);
        List<Group> groups = groupsApi.getGroups().getData();
        if (groups != null) {
            for (Group group : groups) {
                System.out.println(group.toString());
            }
        }

**Comment by Jmfwolf** [comment]
Thank you I will add this to the edits.

**Comment by Jmfwolf** [comment]
Please let me know how the newest release works for you, both issues have been addressed in this release:
https://github.com/onelogin/onelogin-java-sdk/releases/tag/3.1.2

**Comment by tprus** [comment]
Still the same error:

Exception in thread "main" java.lang.IllegalArgumentException: The field `pagination` in the JSON string is not defined in the `GetGroups200Response` properties. JSON: {"status":{"error":false,"code":200,"type":"success","message":"Success"},"pagination":{"before_cursor":null,"after_cursor":null,"previous_link":null,"next_link":null},"data":[{"id":502836,"name":"test","reference":null}]}
	at com.onelogin.client.model.GetGroups200Response.validateJsonObject(GetGroups200Response.java:191)
	at com.onelogin.client.model.GetGroups200Response$CustomTypeAdapterFactory$1.read(GetGroups200Response.java:235)
	at com.onelogin.client.model.GetGroups200Response$CustomTypeAdapterFactory$1.read(GetGroups200Response.java:225)
	at com.google.gson.TypeAdapter$1.read(TypeAdapter.java:199)
	at com.google.gson.Gson.fromJson(Gson.java:963)
	at com.google.gson.Gson.fromJson(Gson.java:928)
	at com.google.gson.Gson.fromJson(Gson.java:877)
	at com.onelogin.client.JSON.deserialize(JSON.java:324)
	at com.onelogin.client.ApiClient.deserialize(ApiClient.java:990)
	at com.onelogin.client.ApiClient.handleResponse(ApiClient.java:1200)
	at com.onelogin.client.ApiClient.execute(ApiClient.java:1124)
	at com.onelogin.client.api.GroupsApi.getGroupsWithHttpInfo(GroupsApi.java:309)
	at com.onelogin.client.api.GroupsApi.getGroups(GroupsApi.java:289)

**Comment by Jmfwolf** [comment]
I will continue looking into this one and bump up the pom

**Comment by tprus** [comment]
Any progress?

**Comment by Jmfwolf** [comment]
I am pretty issue has to do with the generators handling of the Null value. I have been bouncing between repos, but this is prioritized. I will keep you up to date

**Comment by tprus** [comment]
Same problem with getting one app by id (AppsApi).

**Comment by tprus** [comment]
shame

**Comment by Subterrane** [comment]
## Resolution

This issue is specific to the v3 OpenAPI-generated SDK, which used strict JSON validation that failed when encountering fields not explicitly defined in the model (like `pagination`).

We've reverted the `main` branch to **v2.0.2**, the hand-crafted SDK that uses lenient JSON parsing. The v2 code simply extracts the fields it needs and ignores extras, so this error cannot occur.

### To fix this issue:

Update your Maven dependency to v2.0.2:

```xml
<dependency>
    <groupId>com.onelogin</groupId>
    <artifactId>onelogin-java-sdk</artifactId>
    <version>2.0.2</version>
</dependency>
```

The v3 OpenAPI-generated code remains available on the [`v3` branch](https://github.com/onelogin/onelogin-java-sdk/tree/v3) for those who need the newer APIs (Branding, Smart Hooks, API Authorization Servers), but it is no longer the default.
